name: deploy

on:
  push:
    branches: 
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to EC2 & Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.AWS_EC2_IP }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd /var/www/fastapi-app
            git pull origin main
            python3.11 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart fastapi.service
            sudo systemctl reload nginx
