name: test

on:
  pull_request:
  branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Python 3.11
       uses: actions/setup-python@v4
       with:
         python-version: 3.11

      - name: Install dependencies
        run: |
         python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m pytest tests
